# Build and test MVox.
#
# On success, the Documentation workflow (docs.yml) runs automatically
# to build and deploy docs to GitHub Pages.

name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            itk-pkg: libinsighttoolkit4-dev
          - os: ubuntu-latest
            itk-pkg: libinsighttoolkit5-dev

    steps:
    - uses: actions/checkout@v4

    - name: Create MFEM directory
      run: mkdir /home/runner/work/mfem
    - name: Download MFEM
      # NOTE: v4.5.2.tar.gz is extracted to mfem-4.5.2
      working-directory: /home/runner/work/mfem
      run: |
        wget https://github.com/mfem/mfem/archive/refs/tags/v4.5.2.tar.gz
        tar -zxf v4.5.2.tar.gz
    - name: Create MFEM build directory
      run: mkdir /home/runner/work/mfem/build
    - name: Configure MFEM
      working-directory: /home/runner/work/mfem/build
      run: cmake -DCMAKE_INSTALL_PREFIX=/opt/mfem/mfem-4.5 -DCMAKE_CXX_FLAGS="-include cstdint" -DMFEM_USE_ZLIB=YES /home/runner/work/mfem/mfem-4.5.2
    - name: Make MFEM
      working-directory: /home/runner/work/mfem/build
      run: make -j4
    - name: Install MFEM
      working-directory: /home/runner/work/mfem/build
      run: make install

    - name: Install ITK
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.itk-pkg }}

    - name: Create MVox build directory
      run: mkdir /home/runner/work/mvox/build
    - name: Configure MVox
      working-directory: /home/runner/work/mvox/build
      run: cmake -DMFEM_DIR=/opt/mfem/mfem-4.5 /home/runner/work/mvox/mvox
    - name: Make MVox
      working-directory: /home/runner/work/mvox/build
      run: make -j4
    - name: Install MVox
      working-directory: /home/runner/work/mvox/build
      run: sudo make install
    - name: Test mvox
      # TODO: move this to cmake/make test?
      run: |
        cd /home/runner/work/mvox/mvox/examples
        bash boxmesh.sh
        bash brain-tensors.sh

    - name: Archive data
      uses: actions/upload-artifact@v4
      with:
        name: examples-${{ matrix.os }}
        path: /home/runner/work/mvox/mvox/examples
        retention-days: 5
