name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4
    
    - name: Create MFEM directory
      run: mkdir /home/runner/work/mfem
    - name: Download MFEM
      # NOTE: v4.5.2.tar.gz is extracted to mfem-4.5.2
      working-directory: /home/runner/work/mfem
      run: |
        wget https://github.com/mfem/mfem/archive/refs/tags/v4.5.2.tar.gz
        tar -zxf v4.5.2.tar.gz
    - name: Create MFEM build directory
      run: mkdir /home/runner/work/mfem/build
    - name: Configure MFEM
      working-directory: /home/runner/work/mfem/build
      run: cmake -DCMAKE_INSTALL_PREFIX=/opt/mfem/mfem-4.5 -DMFEM_USE_ZLIB=YES /home/runner/work/mfem/mfem-4.5.2
    - name: Make MFEM
      working-directory: /home/runner/work/mfem/build
      run: make -j4
    - name: Install MFEM
      working-directory: /home/runner/work/mfem/build
      run: make install
      
    - name: Install ITK
      run: |
        sudo apt-get update
        sudo apt-get install libinsighttoolkit4-dev
        
    - name: Create MVox build directory
      run: mkdir /home/runner/work/mvox/build
    - name: Configure MVox
      working-directory: /home/runner/work/mvox/build
      run: cmake -DMFEM_DIR=/opt/mfem/mfem-4.5 /home/runner/work/mvox/mvox
    - name: Make MVox
      working-directory: /home/runner/work/mvox/build
      run: make -j4
    - name: Install MVox
      working-directory: /home/runner/work/mvox/build
      run: make install
    - name: Test mvox
      # TODO: move this to cmake/make test?
      run: |
        cd /home/runner/work/mvox/mvox/examples
        bash boxmesh.sh
        bash brain-tensors.sh
        
    - name: Archive data
      uses: actions/upload-artifact@v4
      with:
        name: examples
        path: /home/runner/work/mvox/mvox/examples
        retention-days: 5
